### ISSUE TITLE
Save เป็น pdf บน LibreOffice แล้วภาษาไทยเพี้ยน

### ISSUE THREAD

**Issue by mildronize** [fontuni/boon#16]
ปัญหาตาม หัวข้อ issue เลยครับ ใช้ `LibreOffice Writer Version: 4.2.8.2` ใช้บน `elementary OS 0.3 Freya` base on  `Ubuntu 14.04` ปัญหาเป็นตามรูปนี้เลยครับ 
![image](https://cloud.githubusercontent.com/assets/3647850/9224994/c83789c8-4130-11e5-826d-f45ed340c3dc.png)

ผมลองใช้ เป็นฟอนต์ `Garuda` แล้วใช้ได้ปกติครับ
ผมได้แนบไฟล์ตัวอย่างที่มีปัญหาไว้แล้ว[ที่นี่ครับ](https://www.dropbox.com/s/m688huegq19p4ix/boon-font-problem.zip?dl=0)

ขอบคุณครับ

**Comment by sungsit** [comment]
ผมกำลังเตรียมปรับปรุงฟอนต์ขนานใหญ่อยู่นะครับ จะทำฟีเจอร์ใหม่หมดเลยในเดือนหน้า เดี๋ยวจะแจ้งอีกทีเมื่อมีเวอร์ชั่นใหม่พร้อมให้ทดสอบนะครับ บั๊กอาจจะไม่เหมือนเดิม

**Comment by sungsit** [comment]
ผมลองทดสอบ Boon-v1.0-beta2 https://github.com/fontuni/boon/releases/tag/v1.0-beta2 LibreOffice ใน Archlinux/XFCE4 แล้วไม่มีปัญหาครับ ลองอัพเดตฟอนต์เป็นเวอร์ชั่นใหม่นะครับ
