### ISSUE TITLE
Boon จะมีไฟล์แบบ .eot กับ .svg ให้ download ไหมครับ

### ISSUE THREAD

**Issue by ghost** [fontuni/boon#25]
พอดีผมลองโหลดเอา .ttf ไปแปลงใน Web Font Generator ได้ไฟล์ .eot กับ .svg ไว้ทำ @font-face ใน compass แต่พบว่าเวลาเอาไปแปลงแล้วสระมันลอย อยากทราบว่าจะมี .eot กับ .svg ในอนาคตให้โหลดไหมครับ หรือถ้าจะต้อง compile จาก source ต้องทำอย่างไรบ้างครับ ขอบคุณครับ

**Comment by sungsit** [comment]
ผมเพิ่ม eot & svg ให้แล้วนะครับ https://github.com/fontuni/boon/releases

ไฟล์ eot แปลงโดยใช้ https://github.com/fontello/ttf2eot
ไฟล์ svg แปลงด้วย https://github.com/fontforge/fontforge

ผมไม่มี Windows เลยไม่รู้ว่า eot จะมีปัญหารึเปล่านะครับ คุณลองเช็คดูก่อน ส่วน svg วรรณยุกต์และสระลอยแน่ๆ เพราะมันไม่รองรับ OpenType

เหตุผลที่ eot จาก web font generator มีปัญหากับฟอนต์ไทย ผมเดาว่าเขาทำ subset หรือเอาตัว substitutes หรือ features ไปไม่ครบ เพื่อลดขนาดไฟล์ แต่จริงๆ ยุคนี้ woff2 บีบให้เล็กลงได้ 2-3 เท่าโดยไม่ต้องทำ subset เลย

ส่วนวิธี compile ผมเขียนสคริปต์ python สั่งงาน fontforge และโปรแกรมอื่นเป็น subprocess อีกหลายตัวครับ ลองดูในนี้ครับ https://github.com/fontuni/boon/blob/master/scripts/build-master.py (ผมก็ยังมึนๆ อยู่ว่าจะอธิบายยังไง :)

**Comment by ghost** [comment]
ขอบคุณมากครับ เด๋วถ้ามีเวลาผมจะลองเช็คใน IE ดูให้นะครับ

**Comment by sungsit** [comment]
ถ้า eot ใช้ได้หรือไม่ได้ก็บอกด้วยนะครับ ถ้ามีปัญหาผมจะได้แก้ หรือ ถ้าไม่มีปัญหาก็จะได้ปิด issue นี้ ขอบคุณครับ

**Comment by davelab6** [comment]
Those aren't the best tools. The tools in
https://github.com/bramstein/homebrew-webfonttools are better.

**Comment by ghost** [comment]
ตอนนี้ผมทำ CSS3 @font-face สำหรับฟอนต์บุญไว้แล้วที่ https://github.com/Yutna/BoonFontFace 
ผมได้ลองทดสอบ eot บน IE8 แล้วครับ รู้สึกว่าจะโอเคนะครับ ไม่ได้มีปัญหาอะไรครับ :)

![3](https://cloud.githubusercontent.com/assets/11186504/11209090/98b0dbd8-8d51-11e5-9ee1-be499fd31875.PNG)

**Comment by sungsit** [comment]
@Yutna โอเคเยี่ยมฮะ และ @davelab6 แนะนำเครื่องมือที่ดีกว่าในการแปลงฟอนต์ไว้ ถ้าคุณใช้ Mac & Homebrew http://brew.sh/ ก็จัดการแปลงเองได้เพราะมันดีกว่า web font generator
