### ISSUE TITLE
Correct PS private values for each weight & style

### ISSUE THREAD

**Issue by sungsit** [fontuni/boon#26]
For better auto-hinting results.

**Comment by sungsit** [comment]
@davelab6:  Is there a way to set PS private in FontForge via python?

**Comment by davelab6** [comment]
font.private = [value, value, value]

http://dmtr.org/ff.php#private

**Comment by sungsit** [comment]
@davelab6 Thanks! After a while, I figured out that `private` is a list of tuple.

```
font.private['BlueValues'] = (-20, 0, 600, 620, 780, 800, 810, 830)
font.private['OtherBlues'] = (-225, -210)
font.private['StdHW'] = 100,
font.private['StdVW'] = 137,
```

**Comment by davelab6** [comment]
https://github.com/fontforge/designwithfontforge.com/commit/9f4ee20d4b3cdec6d835ee8614c7c7026e143c19 :)

**Comment by davelab6** [comment]
> For better auto-hinting results

I don't understand this, actually. With which autohinter?

**Comment by sungsit** [comment]
I'm testing AFDKO `authohint` for otf hinting. It requires `StemSnapH` & `StemSnapV` which different from weight to weight so I need to set these values in sfd sources, like `font.private.guess('StemSnapH')`. And it seems to help `ttfautohint` too.
