### ISSUE TITLE
Text wrap the last word to the new line when adding float: right; in CSS on iPad.

### ISSUE THREAD

**Issue by paustria** [fontuni/boon#5]
For example

```
<p class="pull-right">ตัวอย่างคำ</p>
```

On iPad device, it will show

```
ตัวอย่าง
คำ
```

So far I can reproduce on iPad 2, air and mini version. (I assume that this will happen on Safari on all iPad models.) As of now, here is what I did for workaround.

```
.pull-right {
   word-spacing: -1px;
}
```

**Comment by mennwebs** [comment]
If you need this to un-wrap (whole text), you can also use

``` css
.pull-right {
   white-space: nowrap;
}
```

I think the browser treats this as "many words" then breaks it.

**Comment by paustria** [comment]
@MennStudio Thank you for another workaround.
However, my point is there shouldn't be any additional CSS to make the fonts fit in its element.

```
<p class="pull-right">ตัวอย่างคำ</p>
```

Should fit in its own 'p' element under the default behavior of top browsers. (I would say Chrome, Safari, Firefox, and IE.)

At first, I thought it's the text-rendering issue. However, I switched to other fonts and this issue resolved right away. That's why I think it is because of the fonts itself.

**Comment by sungsit** [comment]
[Boon-v1.0-beta2](https://github.com/fontuni/boon/releases/tag/v1.0-beta2) เจอปัญหาเดียวกันไหมครับ?
