### ISSUE TITLE
ไม้เอก ซ่อนใน ป ปลา

### ISSUE THREAD

**Issue by paustria** [fontuni/boon#6]
คำว่า ป่า ไม้เอกซ่อนในป.ปลา ครับผม

**Comment by sungsit** [comment]
ขออภัยที่ตอบช้านะครับ ผมกำลังทำฟอนต์ฟีเจอร์ใหม่หมดเลย บั๊กในเวอร์ชั่นเก่าคง track แล้วแก้ลำบากช่วงนี้

**Comment by mennwebs** [comment]
ไม่มีปัญหาคร้าบบ :D

**Comment by sungsit** [comment]
[Boon-v1.0-beta2](https://github.com/fontuni/boon/releases/tag/v1.0-beta2) ไม่น่ามีปัญหานี้แล้วนะครับ?
